### ISSUE TITLE
jsPDF window is not defined

### ISSUE THREAD

**Issue by alfligno** [kempsteven/vue-html2pdf#31]
Hello guys, I have this error while using the package,
I guess this is came from jspdf

Im using nuxt by the way :)
```
{ ReferenceError: window is not defined
    at ../web/node_modules/jspdf/dist/jspdf.min.js:37:30237
    at module.exports (.../web/node_modules/jspdf/dist/jspdf.min.js:1:124)
    at Object.<anonymous> (.../web/node_modules/jspdf/dist/jspdf.min.js:1:128)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (.../web/node_modules/html2pdf.js/dist/require/html2pdf.cjs.js:10:29)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) statusCode: 500, name: 'ReferenceError' }
```

**Comment by kempsteven** [comment]
Hey man, when using in nuxt you need to do it this way
https://www.npmjs.com/package/vue-html2pdf#using-in-nuxtjs

**Comment by kempsteven** [comment]
Feel free to open this issue if the problem persists!

**Comment by alfligno** [comment]
Thanks man, I thought it wouldn't be necessary, I will try it :)

**Comment by MakeTotalSense** [comment]
Little update, I've been having the same issue, just don't call the component on your script.js and don't call it in your vue components. Then it works just like it should
